### PR TITLE
Chatbot & Styling

### PR DESCRIPTION
**Pull request by Valerietshuma**
# I have completely changed the theme of my portfolio (colors).
home

# Added a different navigation since the old one i had could not fold when on meadia mode, the new one does nd turn into a hamburger and drops down.
nav

# Definitely added a chatbot that is interactive
bot

### CODE REVIEW

**Comment by ClementRep** [comment]
i like the color....combination matter of fact its perfect on my side

**Comment by MulamuMammba** [comment]
The updated style and color combination look awesome. The chatbot and its functionality looks to be up to standard, good job.

**Comment by MbathaSimphiwe** [comment]
Hi, your portfolio It looks great. Please add something on your project page, it looks too blank.

**Comment by Valerietshuma** [comment]
I did add something on my project, it is no longer plain, thanks for the tip @217033Mbatha 
gitproj

**Comment by MbathaSimphiwe** [comment]
Awesome..

**Pull request merged**
